[package]
name = "ordered_map_perf"
version = "0.1.0"
authors = ["Rob <rm.rf.etc@gmail.com>"]
edition = "2018"

[dependencies]
heapless = "0.7.8"
hash32 = "0.1.0"
bencher = "0.1.5"
rand = "0.8.4"
rand_pcg = "0.3.1"

[[bench]]
name = "ordered_map"
harness = false
